# Machine Learning Assignment **1**

# **#Part 1**

**Question 1 of Part 1**

In [ ]:
import numpy as np
print("Array of Ten Zeroes: ")
arrayTenZeroes = np.zeros(shape=(10)) # returns Array of zeros with the given shape, dtype, and order.
print(arrayTenZeroes)
 
print("Array of Ten Ones: ")
arrayTenOnes = np.ones(shape=(10))  #return Array of ones with the given shape, dtype, and order.
print(arrayTenOnes)
 
print("Array of Ten Fives: ")
arrayTenFives = np.ones(shape=(10))*5
print(arrayTenFives)

Array of Ten Zeroes: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Array of Ten Ones: 
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of Ten Fives: 
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**Question 2 of Part 1**

In [ ]:
import numpy as np
array = np.arange(10 , 51 , 2)
print("Even integers from 10 to 50:-")
print(array) 

Even integers from 10 to 50:-
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


**Question 3 of Part 1**

In [ ]:
import numpy as np

randNUm = np.random.uniform(0,1)
print(randNUm)

#It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).
matrix = np.random.random(size =(3, 3)) 
print (matrix) 

0.4085039754152
[[0.38576913 0.87068513 0.48906994]
 [0.24674553 0.02124638 0.56228361]
 [0.13426385 0.0515807  0.86082406]]


**Question 4 of Part 1**

In [ ]:
import numpy as np
import os

# Creating matrix of 3*3
matrix = np.random.random(size =(3, 3)) 
print("Matrix before saving in  text file:-")
print (matrix)

print()

# Saving the matrix in a text file 
np.savetxt('4.txt', matrix) 
print("After Loading the text file containing matrix:-")

# Displaying the contents of the text file
load_matrix = np.loadtxt('4.txt')
print(load_matrix)

Matrix before saving in  text file:-
[[0.86705108 0.5263393  0.73469435]
 [0.98914079 0.05184224 0.72166315]
 [0.84029617 0.64651752 0.66715355]]

After Loading the text file containing matrix:-
[[0.86705108 0.5263393  0.73469435]
 [0.98914079 0.05184224 0.72166315]
 [0.84029617 0.64651752 0.66715355]]


# **#Part 2**

**Question 1 of Part 2**

In [ ]:
from PIL import Image
import numpy as np
import pandas as pd

# open method used to open different extension image file
# Returns type: An image object.
image_frame = Image.open('img.jpg')
image_frame.

#getdata(): Returns the contents of this image as a sequence object containing pixel values.
npframe = np.array(image_frame.getdata())
print(npframe)

# Calling DataFrame constructor on npframe
image_rgb_df = pd.DataFrame(npframe)
print(image_rgb_df)

# store in .csv format
image_rgb_df.to_csv("C:\\Users\\Shantanu Raj\\Desktop\\file.csv") 

[[ 12  24  46]
 [ 14  26  48]
 [ 15  27  49]
 ...
 [102 113 145]
 [101 111 146]
 [ 98 108 143]]
            0    1    2
0          12   24   46
1          14   26   48
2          15   27   49
3          14   26   48
4          17   29   51
...       ...  ...  ...
30105595   98  111  143
30105596   99  112  144
30105597  102  113  145
30105598  101  111  146
30105599   98  108  143

[30105600 rows x 3 columns]




> **Question 2 of Part 2**



In [ ]:
# store in .csv format
image_rgb_df.to_csv("C:\\Users\\Shantanu Raj\\Desktop\\file.csv") 
# skipping last rows and last columns
mydata = pd.read_csv("C:\\Users\\Shantanu Raj\\Desktop\\file.csv", skiprows=[30105600],usecols=[1,2])
mydata.head()
print(mydata)

            0    1
0          12   24
1          14   26
2          15   27
3          14   26
4          17   29
...       ...  ...
30105594   99  112
30105595   98  111
30105596   99  112
30105597  102  113
30105598  101  111

[30105599 rows x 2 columns]




> **Question 3 of Part 2**



In [ ]:
#import pandas as pd
#from datetime import date
#now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
#print(now)
#print(today)
import datetime
from datetime import datetime
print(datetime.now().date())

Today's date:
2021-08-09


# **#Part 3**

In [ ]:
from datetime import datetime
from dateutil import relativedelta

# taking inputs
year = int(input("Enter the year "))
month = int(input("Enter the month "))
day = int(input("Enter the day "))

# datetime: Its a combination of date and time along with the attributes year, month, day, hour, minute, second, microsecond, and tzinfo. 
dob = datetime(year, month, day)
# Pandas to_datetime() method helps to convert string Date time into Python Date time object
today = pd.to_datetime("now").date()

age = relativedelta.relativedelta(today, dob)

years = age.years
months = age.months
days = age.days

print("Your age is", years, "yrs,", months, "months and", days, "days")

Enter the year 1997
Enter the month 7
Enter the day 21
Your age is 24 yrs, 0 months and 18 days
